// Generated by Wrangler by running `wrangler types`

interface Env {
	BETTER_AUTH_SECRET: string;
	NEXT_PUBLIC_BETTER_AUTH_URL: string;
	NEXT_PUBLIC_GOOGLE_AUTH_ID: string;
	GOOGLE_AUTH_SECRET: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_IMAGE_BASE_PATH: string;
	CLOUDFLARE_D1_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	CLOUDFLARE_R2_BUCKET_NAME: string;
	CLOUDFLARE_R2_ID: string;
	CLOUDFLARE_R2_TOKEN: string;
	NODE_ENV: string;
	NEXT_PUBLIC_APP_ENV: string;
	DB: D1Database;
}
